#!/bin/bash
set -x

! git diff  --staged \
  -U0 \
  -Gblockcommit \
  -Gblockgitcommit \
  | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' 2>&1 | read
if [ $? = 1 ]; then
  echo "blocking git commit"
  exit 1
fi