#!/bin/bash

! git diff  --staged \
  --diff-filter=ACM \
  -U0 \
  -Gblockcommit \
  -Gblockgitcommit \
  | grep '^[+]' | grep -Ev '^(\+\+\+ b/)' 2>&1 | read
if [ $? = 1 ]; then
  echo "blocking git commit. macro found blocking gitcommit"
  exit 1
fi